## Vektoren und Matrizen

In [1]:
import numpy as np

#### Fangen wir mit Vektoren an. Wie würden wir diesen Vektor $3\times1$ in NumPy implementieren?

$\vec x = \begin{pmatrix} 2 \\ 1 \\ 3 \end{pmatrix} $

In [2]:
x = np.array([2, 1, 3])
x

array([2, 1, 3])

In [3]:
x + 2

array([4, 3, 5])

In [4]:
c = np.array([2, 2, 2])

In [5]:
x + c

array([4, 3, 5])

In [6]:
x * c

array([4, 2, 6])

In [7]:
x.dot(c)

12

#### Wie können wir nun eine $3\times2$ Matrix erstellen?

${\displaystyle {A = \begin{bmatrix}1&-1&2\\3&2&0\end{bmatrix}}}$

In [8]:
A = np.array([
    [1, -1, 2],
    [3, 2, 0]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  0]])

In [9]:
A.T

array([[ 1,  3],
       [-1,  2],
       [ 2,  0]])

In [10]:
A * c

array([[ 2, -2,  4],
       [ 6,  4,  0]])

In [11]:
A.dot(c)

array([ 4, 10])

#### Wie greifen wir auf Werte einer Matrix zu ?

In [13]:
A

array([[ 1, -1,  2],
       [ 3,  2,  0]])

In [14]:
A[0, :]

array([ 1, -1,  2])

In [15]:
A[0, 0:2]

array([ 1, -1])

In [16]:
A[1]

array([3, 2, 0])