In [1]:
# Nhập thư viện numpy
import numpy as np 
data_numpy = np.loadtxt("E:\Code\Python\Tài liệu Python\KhoaHocDuLieu\Slide_Baigiang\Data_C4\Bai18_Temp.txt")
print(data_numpy)
print("-------------------------------------")
print("kích thước biến:", data_numpy.shape)
print("số chiều của biến:", data_numpy.ndim)
print("kiểu dữ liệu của các phần tử:", data_numpy.dtype)
print("số phần tử:", data_numpy.size)

[[25.65 24.79 24.01 25.06 25.48 24.97]
 [25.31 24.21 24.02 24.93 25.16 24.83]
 [25.05 23.73 23.89 24.79 24.8  24.55]
 ...
 [24.81 24.47 23.4  25.86 25.05 25.29]
 [23.97 24.22 22.95 25.74 24.92 24.87]
 [22.84 23.99 22.59 25.5  24.77 24.57]]
-------------------------------------
kích thước biến: (192, 6)
số chiều của biến: 2
kiểu dữ liệu của các phần tử: float64
số phần tử: 1152


In [2]:
print("---THỐNG KÊ CHO CẢ 6 THÀNH PHỐ---")
print("Nhiệt độ cao nhất: ", data_numpy.max())
print("Nhiệt độ thấp nhất: ", data_numpy.min())
print("NHiệt độ trung bình: ", data_numpy.mean())

---THỐNG KÊ CHO CẢ 6 THÀNH PHỐ---
Nhiệt độ cao nhất:  33.45
Nhiệt độ thấp nhất:  20.93
NHiệt độ trung bình:  26.50222222222222


In [3]:
for i in range(0, 6):
    if (i == 0):
        print("1) Hà Nội")
    if (i == 1):
        print("2) Vinh (Nghệ An)")
    if (i == 2):
        print("3) Đà Nẵng")
    if (i == 3):
        print("4) Nha Trang")
    if (i == 4):
        print("5) TP Hồ Chí Minh")
    if (i == 5):
        print("6) Cà Mau")
    print("Nhiệt độ cao nhất:", data_numpy[:,i].max())
    print("Nhiệt độ thấp nhất:", data_numpy[:,i].min())
    print("Nhiệt độ trung bình:", data_numpy[:,i].mean())

1) Hà Nội
Nhiệt độ cao nhất: 33.45
Nhiệt độ thấp nhất: 21.68
Nhiệt độ trung bình: 27.71229166666667
2) Vinh (Nghệ An)
Nhiệt độ cao nhất: 32.57
Nhiệt độ thấp nhất: 22.6
Nhiệt độ trung bình: 26.719895833333336
3) Đà Nẵng
Nhiệt độ cao nhất: 29.88
Nhiệt độ thấp nhất: 20.93
Nhiệt độ trung bình: 25.522499999999997
4) Nha Trang
Nhiệt độ cao nhất: 28.68
Nhiệt độ thấp nhất: 24.5
Nhiệt độ trung bình: 26.166875000000005
5) TP Hồ Chí Minh
Nhiệt độ cao nhất: 31.06
Nhiệt độ thấp nhất: 23.22
Nhiệt độ trung bình: 26.159218749999997
6) Cà Mau
Nhiệt độ cao nhất: 31.37
Nhiệt độ thấp nhất: 23.99
Nhiệt độ trung bình: 26.73255208333333


In [4]:
data_thongke = np.zeros((3,7))
#sử dụng vòng lặp để lưu dữ liệu của từng thành phố
for i in range(6):
    data_thongke[0,i] = data_numpy[:,i].max()
    data_thongke[1,i] = round(data_numpy[:,i].mean(), 2)
    data_thongke[2,i] = data_numpy[:,i].min()
#cột thống kê chung
data_thongke[0,6] = data_numpy.max()
data_thongke[1,6] = round(data_numpy.mean(), 2)
data_thongke[2,6] = data_numpy.min()
#in
print(data_thongke)
print(type(data_thongke))
print("kích thước:", data_thongke.shape)
np.savetxt("E:/Code/Python/Tài liệu Python/KhoaHocDuLieu/Slide_Baigiang/Data_C4/thongke.txt", data_thongke, fmt='%.2f')

[[33.45 32.57 29.88 28.68 31.06 31.37 33.45]
 [27.71 26.72 25.52 26.17 26.16 26.73 26.5 ]
 [21.68 22.6  20.93 24.5  23.22 23.99 20.93]]
<class 'numpy.ndarray'>
kích thước: (3, 7)
