## Python List vs. NumPy Arrays

Die Ähnlichkeiten: 

-   Beide speichern Daten
-   Beide sind manupulierbar
-   Beide können indexiert und iteriert werden
-   Beide können zerteilt werden


Die Unterschiede: 

-   Listen können häufig genutzt werden für unterschiedliche Daten Typen
-   Arrays werden für arithmetische operationen genutzt (selber Datentyp)

In [2]:
import numpy as np

In [1]:
A = [1, 2, 3, 4]

In [3]:
B = np.array([1, 2, 3, 4])

In [4]:
for e in A:
    print(e)

1
2
3
4


In [5]:
for e in B:
    print(e)

1
2
3
4


In [7]:
A.append(5)
A

[1, 2, 3, 4, 5, 5]

In [8]:
B.append(5)
B

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
A = A + [6]
A

[1, 2, 3, 4, 5, 5, 6]

In [11]:
B = B + [6]
B

array([13, 14, 15, 16])

In [12]:
A2 = []
for e in A:
    A2.append(e + e)
A2

[2, 4, 6, 8, 10, 10, 12]

In [19]:
B = np.array([1,2,3,4])

In [20]:
B

array([1, 2, 3, 4])

In [21]:
B + B

array([2, 4, 6, 8])

In [22]:
B * B

array([ 1,  4,  9, 16])

In [23]:
B ** B

array([  1,   4,  27, 256], dtype=int32)

In [26]:
np.power(B, 2)

array([ 1,  4,  9, 16], dtype=int32)

In [27]:
np.sqrt(B)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [28]:
np.log(B)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [29]:
np.exp(B)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])