## For Loop vs. Skalarprodukt Speedtest

In [2]:
import numpy as np
import time

In [3]:
# Helper Klasse
class Timer(object):
    """
    Record timing information.
    """
    def __init__(self, *steps):
        self._time_per_step = dict.fromkeys(steps)

    def __getitem__(self, item):
        return self.time_per_step[item]

    @property
    def time_per_step(self):
        return {
            step: elapsed_time
            for step, elapsed_time in self._time_per_step.items()
            if elapsed_time is not None and elapsed_time > 0
        }

    def start_for(self, step):
        self._time_per_step[step] = -time.time()

    def stop_for(self, step):
        self._time_per_step[step] += time.time()

In [4]:
A = np.array([1, 2])
A

array([1, 2])

In [5]:
B = np.array([2, 1])
B

array([2, 1])

In [6]:
dot = 0
for i, j in zip(A, B):
    dot += i * j
dot

4

In [8]:
A * A

array([1, 4])

In [9]:
np.sum(A * B)

4

In [10]:
np.dot(A, B)

4

In [11]:
A.dot(B)

4

### Speedtest

In [12]:
main_timer = Timer('loop', 'numpy')

In [13]:
A = np.random.randn(100)
B = np.random.randn(100)
T = 1000
A

array([-0.46808355,  0.9988787 , -0.47214694, -1.54511136, -0.81286203,
        0.30273397,  0.28117534,  0.03028102, -0.06614801,  2.34762513,
        0.52044331, -2.0845661 , -1.55083536,  0.09710963,  2.09311211,
       -0.28053165, -0.52964506,  0.38580504, -0.84116826,  0.4624197 ,
       -0.74880798, -0.64667097,  0.68970764,  0.25588497,  0.08127432,
       -0.1309744 , -0.74587572,  0.61504915, -0.14872891, -0.80521677,
        0.84080285,  0.53430502, -0.41892501,  0.7812082 ,  0.10063993,
        1.61187234,  0.83960402,  0.47522293,  1.93070452,  0.32965137,
       -0.6539233 , -1.16794012, -0.60004655,  0.36493105, -1.68131924,
       -0.21665403, -0.94215397,  0.75571729,  0.48813437,  0.86205839,
        1.37812106, -0.84972028, -1.23503312, -0.0471597 , -0.91173814,
        0.17515154, -0.80729537, -0.22631901,  1.95047671,  1.05092734,
        0.70882274, -0.18547958, -1.77511956,  1.15046935,  2.43366376,
        1.3566465 , -1.26013468, -0.07676897, -0.81033972, -0.22

In [20]:
def python_dot(A, B):
    dot = 0
    for i, j in zip(A, B):
        dot += i * j
    return dot

In [21]:
main_timer.start_for('loop')
for _ in range(T):
    python_dot(A, B)
main_timer.stop_for('loop')

In [22]:
main_timer.start_for('numpy')
for _ in range(T):
    A.dot(B)
main_timer.stop_for('numpy')

In [23]:
print("Numpy ist schneller um ", (main_timer['loop'] / main_timer['numpy']))

Numpy ist schneller um  15.490757304710794
