## Automatisch Matrizen generieren

In [1]:
import numpy as np

#### Wie war es bisher?

#### Wie können wir nun Vektoren und Matrizen generieren?

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[0.74023069],
       [0.50288622],
       [0.66046372],
       [0.26971584],
       [0.66887599]])

#### Wie generieren wir Werte $\geq 0$ und $\leq 0$ ?

Die Lösung ist mithilfe der Normalverteilung! Gerne mehr hier: https://de.wikipedia.org/wiki/Normalverteilung

Die Normalverteilung $X \sim \mathcal{N}(\mu,\,\sigma^{2})\,$ hat Standardwerte wie das mean $\mu = 0$ und die Varianz $\sigma^{2} = 1$

array([[-1.59880233,  1.01427804, -0.68745601,  0.42785217,  0.08260566],
       [-0.61331649, -0.52036382, -0.9031695 , -0.06225542,  0.94646579],
       [ 0.75084202, -0.36931812,  1.80858652, -0.51750007, -0.9088839 ],
       [-0.09311925, -0.24769591,  0.03948517,  0.03740283, -0.22236699],
       [-0.83478441, -0.85105934,  1.04152626,  0.8810055 , -0.2860886 ],
       [ 0.07314324, -1.26731871,  1.23708909, -1.71734911,  2.2168763 ],
       [ 0.91786235,  0.0941499 ,  1.02110538,  1.38411353,  0.18630961],
       [ 1.69504651, -0.93010948, -0.28699777, -0.37405503,  0.61057045],
       [-1.04524779, -0.08358173, -0.7319478 , -1.80042385,  0.29886647],
       [ 1.15277876, -0.76602279, -1.31865232,  0.60042498,  0.83503781]])

0.006310755563999819

0.8804222285367603