## Automatisch Matrizen generieren

In [17]:
import numpy as np

#### Wie war es bisher?

In [18]:
np.array([0, 1, 2])

array([0, 1, 2])

#### Wie können wir nun Vektoren und Matrizen generieren?

In [19]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
Z = np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
B = np.ones((5, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
W = np.random.random((5,1))
W

array([[0.17954816],
       [0.08509342],
       [0.34038314],
       [0.38146468],
       [0.05824509]])

#### Wie generieren wir Werte $\geq 0$ und $\leq 0$ ?

Die Lösung ist mithilfe der Normalverteilung! Gerne mehr hier: https://de.wikipedia.org/wiki/Normalverteilung

Die Normalverteilung $X \sim \mathcal{N}(\mu,\,\sigma^{2})\,$ hat Standardwerte wie das mean $\mu = 0$ und die Varianz $\sigma^{2} = 1$

In [23]:
X = np.random.randn(10,5) # kein Tuple mehr!
X

array([[ 3.52834518e-01, -1.20568600e+00, -6.39059057e-01,
         2.65483085e-01,  5.26039673e-01],
       [ 1.16834515e+00,  9.70456490e-01, -1.52416703e+00,
        -8.24058741e-01, -3.59767915e-01],
       [ 2.46586664e-01, -5.66915259e-01,  4.27602329e-01,
         6.80156166e-01, -1.13058645e+00],
       [ 8.62369575e-01, -8.05610312e-01,  1.02374468e+00,
        -2.47542066e-04,  2.87715174e-01],
       [-6.88299802e-01,  1.48897487e+00,  6.74221817e-02,
        -9.55996734e-01, -1.09477826e+00],
       [ 1.02307023e+00,  1.33855897e+00, -5.55424485e-01,
         7.98800141e-02, -1.18703108e+00],
       [ 2.03348527e+00,  3.04165171e-01, -3.70758591e-01,
        -2.47163106e-01, -7.95738312e-01],
       [ 1.32495089e+00, -5.76845102e-01, -5.09027714e-01,
        -6.41798682e-01,  1.22517670e+00],
       [-4.56473781e-01,  9.62800444e-01, -5.78614902e-01,
        -9.53438398e-02,  9.97359856e-01],
       [-1.96923445e+00,  2.00686064e+00,  8.02396034e-01,
         1.35178875e+00

In [24]:
X.mean()

0.07511930976731104

In [25]:
X.var()

0.8788037269359801